[package]
name = "furball"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tabby = { git = "https://github.com/copycatdb/tabby.git", branch = "main", default-features = false, features = ["sync"] }
parking_lot = "0.12"
